version: '2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - jpg
    ports:
      - '3000:3000'
networks:
  jpg:
    driver: bridge
